"""add phne number on users table

Revision ID: c4425f0e9b10
Revises: 6fbb7cda63e4
Create Date: 2022-09-26 19:09:56.323412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4425f0e9b10'
down_revision = '6fbb7cda63e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
